haskell-tiny-toy:
	mkdir -p build
	ghc -O2 -o build/tiny-toy tiny-toy

haskell-slightly-harder:
	mkdir -p build
	ghc -O2 -o build/slightly-harder slightly-harder

haskell-three-way-xor:
	mkdir -p build
	ghc -O2 -o build/three-way-xor three-way-xor

clean:
	rm *.hi
	rm *.o
	rm -rf build/
