haskell-tiny-toy:
	mkdir -p build
	ghc -O2 -o build/TinyToy TinyToy

haskell-slightly-harder:
	mkdir -p build
	ghc -O2 -o build/SlightlyHarder SlightlyHarder

haskell-three-way-xor:
	mkdir -p build
	ghc -O2 -o build/ThreeWayXor ThreeWayXor

clean:
	rm *.hi
	rm *.o
	rm -rf build/
